# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

ci:
  autofix_commit_msg: "[pre-commit.ci] auto code formatting"
  autofix_prs: false
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: quarterly
  skip: []
  submodules: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
        types_or: [c, c++]
        args: ["-fallback-style=none", "-style=file", "-i"]
      - id: clang-format
        name: clang-format (libcxx stubs)
        files: '^libcxx/'
        types: [file]
        types_or: []
        args: ["-fallback-style=none", "-style=file", "-i"]

  - repo: https://github.com/sirosen/texthooks
    rev: 0.7.1
    hooks:
      - id: fix-smartquotes

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: ["--toml", "pyproject.toml"]

  - repo: https://github.com/rapidsai/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: verify-copyright
        args: [--fix, --spdx]
        files: '\.(cmake|cpp|hpp|sh)$'

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.25.2
    hooks:
      - id: zizmor

  - repo: local
    hooks:
      - id: cmake-format
        name: cmake-format
        entry: ./ci/checks/run-cmake-format.sh cmake-format
        language: python
        types: [cmake]
        additional_dependencies: [cmakelang==0.6.13]
      - id: cmake-lint
        name: cmake-lint
        entry: ./ci/checks/run-cmake-format.sh cmake-lint
        language: python
        types: [cmake]
        additional_dependencies: [cmakelang==0.6.13]
